# Generated by Django 5.2 on 2025-07-21 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('frame_list', models.JSONField(blank=True, null=True)),
                ('fixed_frame', models.IntegerField(blank=True, null=True)),
                ('release_frame', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('release_frame_knee', models.JSONField(blank=True, null=True)),
                ('release_frame_ankle', models.JSONField(blank=True, null=True)),
                ('ball_speed', models.JSONField(blank=True, null=True)),
                ('release_angle_height', models.JSONField(blank=True, null=True)),
                ('skeleton_coords', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
