# Generated by Django 5.2 on 2025-09-19 01:57

import analysis.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('throwing_hand', models.CharField(blank=True, choices=[('R', '우투'), ('L', '좌투')], max_length=10, null=True)),
                ('batting_hand', models.CharField(blank=True, choices=[('R', '우타'), ('L', '좌타'), ('S', '양타')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('team', models.CharField(max_length=50)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='analysis.player')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('player', 'year', 'team')},
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('era', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('games', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('holds', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('innings_pitched', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('hits_allowed', models.IntegerField(default=0)),
                ('home_runs_allowed', models.IntegerField(default=0)),
                ('walks', models.IntegerField(default=0)),
                ('hit_by_pitch', models.IntegerField(default=0)),
                ('strikeouts', models.IntegerField(default=0)),
                ('runs_allowed', models.IntegerField(default=0)),
                ('earned_runs', models.IntegerField(default=0)),
                ('player_season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='analysis.playerseason')),
            ],
        ),
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_name', models.CharField(blank=True, max_length=255, null=True)),
                ('video_file', models.FileField(max_length=255, upload_to=analysis.models.get_video_upload_path)),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('frame_list', models.JSONField(blank=True, null=True)),
                ('fixed_frame', models.IntegerField(blank=True, null=True)),
                ('release_frame', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('release_frame_knee', models.JSONField(blank=True, null=True)),
                ('release_frame_ankle', models.JSONField(blank=True, null=True)),
                ('ball_speed', models.JSONField(blank=True, null=True)),
                ('release_angle_height', models.JSONField(blank=True, null=True)),
                ('skeleton_coords', models.JSONField(blank=True, null=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='analysis.player')),
            ],
        ),
    ]
