# Generated by Django 5.2 on 2025-09-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoanalysis',
            name='video_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
