# Generated by Django 5.2 on 2025-08-10 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_player_videoanalysis_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='batting_hand',
            field=models.CharField(blank=True, choices=[('R', '우타'), ('L', '좌타'), ('S', '양타')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='throwing_hand',
            field=models.CharField(blank=True, choices=[('R', '우투'), ('L', '좌투')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlayerSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('team', models.CharField(max_length=50)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='analysis.player')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('player', 'year', 'team')},
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('era', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('games', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('holds', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('innings_pitched', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('hits_allowed', models.IntegerField(default=0)),
                ('home_runs_allowed', models.IntegerField(default=0)),
                ('walks', models.IntegerField(default=0)),
                ('hit_by_pitch', models.IntegerField(default=0)),
                ('strikeouts', models.IntegerField(default=0)),
                ('runs_allowed', models.IntegerField(default=0)),
                ('earned_runs', models.IntegerField(default=0)),
                ('player_season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='analysis.playerseason')),
            ],
        ),
    ]
