# Generated by Django 5.2 on 2025-09-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_videoanalysis_video_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalysis',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
